// Employees list
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEE_SUCCESS';
export const GET_EMPLOYEES_FAILURE = 'GET_EMPLOYEE_FAILURE';
//One employee
export const GET_EMPLOYEE_SUCCESS = 'GET_EMPLOYEE_SUCCESS';
export const GET_EMPLOYEE_FAILURE = 'GET_EMPLOYEE_FAILURE';
//Create employee
export const CREATE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';
export const CREATE_EMPLOYEE_FAILURE = 'DELETE_EMPLOYEE_FAILURE';
//Update employee
export const UPDATE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';
export const UPDATE_EMPLOYEE_FAILURE = 'DELETE_EMPLOYEE_FAILURE';
//Delete employee
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_FAILURE = 'DELETE_EMPLOYEE_FAILURE';
